### ISSUE TITLE
control

### ISSUE THREAD

**Issue by Serzh812** [przemykomo/fansmod#1]
make adjustable fans, from one block and up

**Comment by przemykomo** [comment]
Ok, I'm making now new in-game configurable fan.
Also I'm going to make mod config to adjust all fans.
Thanks for idea.

**Comment by przemykomo** [comment]
I just finished version 1.1.1.0 of mod which adds configurable fan.
309969b24e8d269ddcdf0fae3679f3dbc83fb5d2
I'm going to work on config file from now.

**Comment by przemykomo** [comment]
Done
